include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  mt65xx_lcm_list.o
obj-y += hx8394_hd720_dsi_vdo_truly.o
obj-y += otm1285a_hd720_dsi_vdo_tianma.o
obj-y += hx8394d_hd720_dsi_vdo_truly.o
obj-y += hx8392b_hd720_dsi_vdo_tianma.o
